Repository Kritika30032002/ReactCreations, pull requests merged in 2023-12, with the labels that each got.

#83 Added News App in news folder
  news/.gitignore
  news/README.md
  news/package-lock.json
  news/package.json
  news/public/favicon.ico
  news/public/index.html
  news/public/logo192.png
  news/public/logo512.png
  news/public/manifest.json
  news/public/robots.txt
  news/src/App.css
  news/src/App.js
  news/src/App.test.js
  news/src/components/Clock.js
  news/src/components/NavBar.js
  news/src/components/News.js
  news/src/components/NewsItem.js
  news/src/components/Spinner.js
  news/src/components/loading.gif
  news/src/components/read.png
  news/src/components/read_more.png
  news/src/index.css
  news/src/index.js
  news/src/logo.svg
  news/src/reportWebVitals.js
  news/src/setupTests.js
Labels: hard

#95 added student management website
  Student Management/.gitignore
  Student Management/README.md
  Student Management/package-lock.json
  Student Management/package.json
  Student Management/public/index.html
  Student Management/src/App.jsx
  Student Management/src/assets/logo.png
  Student Management/src/assets/timetable.pdf
  Student Management/src/components/academics/Academics.jsx
  Student Management/src/components/academics/academics.css
  Student Management/src/components/contact/Contact.jsx
  Student Management/src/components/contact/contact.css
  Student Management/src/components/footer/Footer.jsx
  Student Management/src/components/footer/footer.css
  Student Management/src/components/header/Header.jsx
  Student Management/src/components/header/header.css
  Student Management/src/components/navbar/Navbar.jsx
  Student Management/src/components/navbar/navbar.css
  Student Management/src/components/sidebar/Sidebar.jsx
  Student Management/src/components/sidebar/sidebar.css
  Student Management/src/components/technology/Technology.jsx
  Student Management/src/components/technology/technology.css
  Student Management/src/index.css
  Student Management/src/index.js
Labels: Codepeak23, hard

#102 Added Netflix-UI Clone
  Netflix-UI-Clone/.gitignore
  Netflix-UI-Clone/README.md
  Netflix-UI-Clone/netflix-api/controllers/UserController.js
  Netflix-UI-Clone/netflix-api/models/UserModel.js
  Netflix-UI-Clone/netflix-api/package-lock.json
  Netflix-UI-Clone/netflix-api/package.json
  Netflix-UI-Clone/netflix-api/routes/UserRoutes.js
  Netflix-UI-Clone/netflix-api/server.js
  Netflix-UI-Clone/netflix-api/yarn.lock
  Netflix-UI-Clone/netflix-ui/.gitignore
  Netflix-UI-Clone/netflix-ui/README.md
  Netflix-UI-Clone/netflix-ui/package.json
  Netflix-UI-Clone/netflix-ui/public/favicon.ico
  Netflix-UI-Clone/netflix-ui/public/index.html
  Netflix-UI-Clone/netflix-ui/public/logo192.png
  Netflix-UI-Clone/netflix-ui/public/logo512.png
  Netflix-UI-Clone/netflix-ui/public/manifest.json
  Netflix-UI-Clone/netflix-ui/public/robots.txt
  Netflix-UI-Clone/netflix-ui/src/App.js
  Netflix-UI-Clone/netflix-ui/src/assets/card.jpg
  Netflix-UI-Clone/netflix-ui/src/assets/home.jpg
  Netflix-UI-Clone/netflix-ui/src/assets/homeTitle.webp
  Netflix-UI-Clone/netflix-ui/src/assets/login.jpg
  Netflix-UI-Clone/netflix-ui/src/assets/logo-logomark.png
  Netflix-UI-Clone/netflix-ui/src/assets/logo.png
  Netflix-UI-Clone/netflix-ui/src/assets/tv.png
  Netflix-UI-Clone/netflix-ui/src/assets/video-tv-in-0819.mp4
  Netflix-UI-Clone/netflix-ui/src/assets/video.mp4
  Netflix-UI-Clone/netflix-ui/src/components/BackgroundImage.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Card.jsx
  Netflix-UI-Clone/netflix-ui/src/components/CardSlider.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Enjoy.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Faq.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Header.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Navbar.jsx
  Netflix-UI-Clone/netflix-ui/src/components/NotAvailable.jsx
  Netflix-UI-Clone/netflix-ui/src/components/SelectGenre.jsx
  Netflix-UI-Clone/netflix-ui/src/components/Slider.jsx
  Netflix-UI-Clone/netflix-ui/src/index.css
  Netflix-UI-Clone/netflix-ui/src/index.js
  Netflix-UI-Clone/netflix-ui/src/pages/Login.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/Movies.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/Netflix.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/Player.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/Signup.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/TVShows.jsx
  Netflix-UI-Clone/netflix-ui/src/pages/UserListedMovies.jsx
  Netflix-UI-Clone/netflix-ui/src/store/index.js
  Netflix-UI-Clone/netflix-ui/src/utils/constants.js
  Netflix-UI-Clone/netflix-ui/src/utils/firebase-config.js
  Netflix-UI-Clone/netflix-ui/yarn.lock
Labels: Codepeak23, hard

#113 added github api project
  GITHUB RESTapi project/.eslintrc.cjs
  GITHUB RESTapi project/.gitignore
  GITHUB RESTapi project/README.md
  GITHUB RESTapi project/index.html
  GITHUB RESTapi project/package-lock.json
  GITHUB RESTapi project/package.json
  GITHUB RESTapi project/public/vite.svg
  GITHUB RESTapi project/src/App.css
  GITHUB RESTapi project/src/App.jsx
  GITHUB RESTapi project/src/Detail.css
  GITHUB RESTapi project/src/Details.jsx
  GITHUB RESTapi project/src/Home.jsx
  GITHUB RESTapi project/src/assets/react.svg
  GITHUB RESTapi project/src/index.css
  GITHUB RESTapi project/src/main.jsx
  GITHUB RESTapi project/vite.config.js
Labels: Codepeak23, medium
